shows:
  self-hosted:
    fireside_url: https://selfhosted.show
    jb_url: https://www.jupiterbroadcasting.com/show/self-hosted
    header_image: /images/shows/selfhosted.png
    acronym: SSH
    name: Self-Hosted
  coder-radio:
    fireside_url: https://coder.show
    jb_url: https://www.jupiterbroadcasting.com/show/coderradio
    header_image: /images/shows/coderradio.png
    acronym: CR
    name: Coder Radio
  linux-action-news:
    fireside_url: https://linuxactionnews.com
    jb_url: https://www.jupiterbroadcasting.com/show/linux-action-news
    header_image: /images/shows/linux-action-news.png
    acronym: LAN
    name: Linux Action News
  linux-unplugged:
    fireside_url: https://linuxunplugged.com
    jb_url: https://www.jupiterbroadcasting.com/show/linuxun
    header_image: /images/shows/linuxun.png
    acronym: LUP
    name: LINUX Unplugged
  extras:
    fireside_url: https://extras.show
    jb_url: https://www.jupiterbroadcasting.com/show/extras
    header_image: /images/shows/extras.png
    acronym: JE
    name: Jupiter EXTRAS
  office-hours:
    fireside_url: https://www.officehours.hair
    jb_url: https://www.jupiterbroadcasting.com/show/office
    header_image: /images/shows/officehours.png
    acronym: OH
    name: Office Hours
# Map usernames of hosts/guests as they appear in fireside to how we want to save them
usernames_map:
  chrislas: chris
  wespayne: wes
  alexktz: alex
  brentgervais: brent