version: '3'
services:
  scraper:
    image: jb-scraper
    container_name: jb-scraper
    environment:
      # - LATEST_ONLY=true
      # - LOG_LVL=10
      - DATA_DIR=/data
    build:
      context: .
    volumes:
      - ./data:/data

